### ISSUE TITLE
CTFdSharp Project

### ISSUE THREAD

**Issue by ghost** [Still34/ph-ctf#5]
Hello,
Didnt the mt-hack team use to have a CTFdSharp project on Github? What happened to that?

**Comment by Still34** [comment]
I kinda scrapped it due to lack of interest. We were planning on making a bot utilizing the wrapper library, but ultimately decided to scrap it due to the amount of time it might take.

The thing with CTFd is its API is... Unintuitive to say the least, at least with its authentication flow.

**Comment by bferguson-sentek** [comment]
Yeah thats where we are stuck. We are only able to sign in as one user for the entire app. There doesnt seem to be a way to allow multiple users access to their own account.

**Comment by Still34** [comment]
The only workaround I can think of is to spawn multiple clients for this. While yes, this is doable, it is not ideal. The best way to solve this is to encourage the CTFd team to better implement their APIs. Given the current state of the project, writing an API client is rather unfeasible and or tedious.

**Comment by bferguson-sentek** [comment]
I came to the exact same conclusion. Thanks for confirming my research.
